#version 460

layout(local_size_x = 128) in;

#import <voxy:lod/section.glsl>

struct DrawCommand {
    uint vertexCount;
    uint instanceCount;
    uint firstVertex;
    uint firstInstance;
};

layout(binding = 1, std430) readonly buffer MetadataBuffer {
    SectionMeta sectionData[];
};
layout(binding = 2, std430) readonly buffer RenderListBuffer {
    uint visibleCount;
    uint indirectLookup[];
};
layout(binding = 3, std430) writeonly buffer DrawCommandsBuffer {
    DrawCommand commands[];
};
layout(binding = 4, std430) buffer DrawCountBuffer {
    uint drawCount;
};
layout(binding = 5, std430) readonly buffer CmdGenConfigBuffer {
    uint metadataSectionCapacity;
    uint renderListCapacity;
};


uint extractTranslucentQuadCount(SectionMeta meta) {
    return meta.b.x & 0xFFFFu;
}

uint extractOpaqueQuadCount(SectionMeta meta) {
    uvec4 counts = meta.b;
    return ((counts.x >> 16u) & 0xFFFFu)
        + (counts.y & 0xFFFFu)
        + ((counts.y >> 16u) & 0xFFFFu)
        + (counts.z & 0xFFFFu)
        + ((counts.z >> 16u) & 0xFFFFu)
        + (counts.w & 0xFFFFu)
        + ((counts.w >> 16u) & 0xFFFFu);
}

void main() {
    uint drawIndex = gl_GlobalInvocationID.x;
    uint safeVisibleCount = min(visibleCount, renderListCapacity);
    if (drawIndex >= safeVisibleCount) {
        return;
    }

    uint sectionId = indirectLookup[drawIndex];
    if (sectionId >= metadataSectionCapacity) {
        if (drawIndex == 0u) {
            drawCount = 0u;
        }
        return;
    }
    SectionMeta meta = sectionData[sectionId];
    uint quadCount = extractOpaqueQuadCount(meta);

    DrawCommand cmd;
    cmd.vertexCount = quadCount * 4u;
    cmd.instanceCount = 1u;
    cmd.firstVertex = (extractQuadStart(meta) + extractTranslucentQuadCount(meta)) * 4u;
    cmd.firstInstance = drawIndex;
    commands[drawIndex] = cmd;

    if (drawIndex == 0u) {
        drawCount = safeVisibleCount;
    }
}
