#version 460

layout(local_size_x = 128) in;

layout(binding = 1, std430) readonly volatile buffer MetadataUintBuffer {
    uint metadataWord;
};
layout(binding = 2, std430) readonly volatile buffer Binding2UintBuffer {
    uint binding2Word;
};

void main() {
    if (gl_GlobalInvocationID.x != 0u) return;
    uint combined = metadataWord ^ binding2Word;
    if (combined == 0xffffffffu) memoryBarrierBuffer();
}
