#version 460

layout(local_size_x = 1) in;

layout(binding = 5, std430) buffer CmdGenConfigBuffer {
    uint metadataSectionCapacity;
    uint renderListCapacity;
    uint geometryCapacityQuads;
    uint drawCommandCapacity;
    uint drawCountCapacityWords;
    uint flags;
};

void main() {
    uint value = flags;
    if (value == 0xffffffffu) {
        flags = metadataSectionCapacity
            + renderListCapacity
            + geometryCapacityQuads
            + drawCommandCapacity
            + drawCountCapacityWords;
    }
}
